import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

export const GSD_MOA_MODEL_IDS = [
  "gpt55-glm52-single",
  "gpt55-glm52-advisor",
  "gpt55-glm52-full",
  "gpt55-glm52-auto",
  "gpt55-gemini35flash-single",
  "gpt55-gemini35flash-advisor",
  "gpt55-gemini35flash-full",
  "gpt55-gemini35flash-auto",
  "gpt55-glm52-gemini35flash-full",
  "gpt55-cliproxycodex-single",
  "gpt55-cliproxycodex-advisor",
  "gpt55-cliproxycodex-full",
  "gpt55-cliproxycodex-auto",
  "gpt55-cliproxycodex-glm52-gemini35flash-full",
  "gpt55-cliproxycodex-glm52-claudeopus48-full",
  "glm52-zai-gpt55-cliproxycodex-full",
  "glm52-zai-gpt55-cliproxycodex-nosynth-full",
] as const;

export type GsdMoaModelId = (typeof GSD_MOA_MODEL_IDS)[number];

export const GSD_MOA_MODELS: ProviderModelConfig[] = [
  {
    id: "gpt55-glm52-single",
    name: "GSD MoA: GPT-5.5 + GLM-5.2 (Single)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-glm52-advisor",
    name: "GSD MoA: GPT-5.5 + GLM-5.2 (Advisor)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-glm52-full",
    name: "GSD MoA: GPT-5.5 + GLM-5.2 (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-glm52-auto",
    name: "GSD MoA: GPT-5.5 + GLM-5.2 (Auto)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-gemini35flash-single",
    name: "GSD MoA: GPT-5.5 + Gemini 3.5 Flash (Single)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-gemini35flash-advisor",
    name: "GSD MoA: GPT-5.5 + Gemini 3.5 Flash (Advisor)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-gemini35flash-full",
    name: "GSD MoA: GPT-5.5 + Gemini 3.5 Flash (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-gemini35flash-auto",
    name: "GSD MoA: GPT-5.5 + Gemini 3.5 Flash (Auto)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-glm52-gemini35flash-full",
    name: "GSD MoA: GPT-5.5 + GLM-5.2 + Gemini 3.5 Flash (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-single",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex (Single)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-advisor",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 (Advisor)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-full",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-auto",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 (Auto)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-glm52-gemini35flash-full",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 + Gemini Flash (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "gpt55-cliproxycodex-glm52-claudeopus48-full",
    name: "GSD MoA: GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 + Claude Opus 4.8 (Full MoA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
    contextWindow: 272000,
    maxTokens: 128000,
  },
  {
    id: "glm52-zai-gpt55-cliproxycodex-full",
    name: "GSD MoA: GLM-5.2 driver + GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 refs (Full MoA)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 8192,
  },
  {
    id: "glm52-zai-gpt55-cliproxycodex-nosynth-full",
    name: "GSD MoA: GLM-5.2 driver + GPT-5.5 via CLIProxyAPI Codex + GLM-5.2 refs (No Synth)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 8192,
  },
];
